### ISSUE TITLE
Support Environment Variables

### ISSUE THREAD

**Issue by filipninja** [garnaat/kappa#101]
AWS Lambda now support environment variables, which is much better way of providing environment specific configuration then bundling json files.

https://aws.amazon.com/about-aws/whats-new/2016/11/aws-lambda-supports-environment-variables/
http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html

Could it be supported by kappa?

**Comment by filipninja** [comment]
oh, there is already pull request for that. Any chance for marge and release?

**Comment by josegonzalez** [comment]
Link?

**Comment by filipninja** [comment]
https://github.com/garnaat/kappa/pull/98

**Comment by josegonzalez** [comment]
It was merged.
