### ISSUE TITLE
Installation fails on python 3.5 amazon-linux docker

### ISSUE THREAD

**Issue by hemanth7787** [garnaat/kappa#123]
**(env)bash-4.2# pip --version
pip 6.0.8 from /app/env/local/lib/python3.5/site-packages (python 3.5)
(env)bash-4.2# pip install kappa**

> You are using pip version 6.0.8, however version 9.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Collecting kappa
>   Using cached kappa-0.7.0.tar.gz
>     Traceback (most recent call last):
>       File "<string>", line 20, in <module>
>       File "/tmp/pip-build-j59n2qmb/kappa/setup.py", line 54, in <module>
>         run_setup()
>       File "/tmp/pip-build-j59n2qmb/kappa/setup.py", line 22, in run_setup
>         long_description=open_file('README.rst').read(),
>       File "/app/env/lib64/python3.5/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2339: ordinal not in range(128)
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>     
>       File "<string>", line 20, in <module>
>     
>       File "/tmp/pip-build-j59n2qmb/kappa/setup.py", line 54, in <module>
>     
>         run_setup()
>     
>       File "/tmp/pip-build-j59n2qmb/kappa/setup.py", line 22, in run_setup
>     
>         long_description=open_file('README.rst').read(),
>     
>       File "/app/env/lib64/python3.5/encodings/ascii.py", line 26, in decode
>     
>         return codecs.ascii_decode(input, self.errors)[0]
>     
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2339: ordinal not in range(128)
>     
>     ----------------------------------------
>     Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j59n2qmb/kappa

**(env)bash-4.2# pip install --upgrade pip**

> You are using pip version 6.0.8, however version 9.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Collecting pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
>   Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
>     100% |################################| 1.3MB 115kB/s 
> Installing collected packages: pip
>   Found existing installation: pip 6.0.8
>     Uninstalling pip-6.0.8:
>       Successfully uninstalled pip-6.0.8
> 
> Successfully installed pip-9.0.1

**(env)bash-4.2# pip install kappa**

> Collecting kappa
>   Using cached kappa-0.7.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-5yx4v_q2/kappa/setup.py", line 54, in <module>
>         run_setup()
>       File "/tmp/pip-build-5yx4v_q2/kappa/setup.py", line 22, in run_setup
>         long_description=open_file('README.rst').read(),
>       File "/app/env/lib64/python3.5/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2339: ordinal not in range(128)
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5yx4v_q2/kappa/
>

**Comment by hemanth7787** [comment]
closed as its a very specific case.

**Comment by CKrawczyk** [comment]
In case anyone else runs across this I found a solution, set the language env variable in the docker container: `ENV LANG=en_US.UTF-8`.
