### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by alhafoudh** [garnaat/kappa#34]
As introduced on re:invent 2015, AWS Lambda now supports python as runtime language.

**Comment by garnaat** [comment]
The current version of kappa will work with Python as long as you specify it in the config file, e.g.:

      runtime: python2.7

And you install any dependencies as described [here](http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html).

Note, however, that I am working on a major new release of kappa that will include a full Python sample as well as support for new Lambda features like versioning and aliases.  I hope to have that out in the next few days.

**Comment by alhafoudh** [comment]
Great, thanks!

**Comment by alhafoudh** [comment]
The thing is, that AWS requires the contents of the lib/python2.7/site-packages/ directory to be zipped, not whole directory structure that virtualenv creates :(

Right now kappa does not support running "pre-update" commands to prepare the package like copy the necessary files to some staging directory so the zipping would be done from other directory.

**Comment by garnaat** [comment]
Or, we could add an entry to the config file that represents the command to run in the code directory to install the dependencies.  This command would be run before the code was zipped and uploaded to Lambda.

**Comment by alhafoudh** [comment]
Yes, something like that.

Currently I have Makefile like this:

```
PROJECT_NAME = lambda_python_demo
DIST_DIR = ./dist
KAPPA_CONFIG = ./config.yml

PROJECT_FILES = ./$(PROJECT_NAME)/*.py
VIRTUALENV_SITE_PACKAGES = ./$(PROJECT_NAME)/lib/python2.7/site-packages
ZIP_FILE = ./$(PROJECT_NAME).zip

KAPPA = kappa --debug $(KAPPA_CONFIG)

update_code: copy
	$(KAPPA) update_code

copy: clean
	cp -R $(PROJECT_FILES) $(VIRTUALENV_SITE_PACKAGES)/* $(DIST_DIR)

clean:
	rm -rf $(DIST_DIR)/*

%:
	$(KAPPA) $@
```

**Comment by ojcitt** [comment]
Hi,

If I'm using PIP instead of VirtualEnv to install my library dependencies into my Lambda package directory, do I need to do anything with a custom command or Makefile?

Thanks,
Jay

**Comment by samuel-soubeyran** [comment]
Hello,
Any update on this ?

A potential solution could be to add a "path" parameter in the config which would hold a list of directories / files whose content would be added to the zip...
We could also use the requirements.txt file to add the dependencies to the zip, but this might be a bit too specific to python....

Thanks,

Samuel

**Comment by lashex** [comment]
Just wondering if there's been any progress on this. Adding the Python Lambda Function and dependencies using Kappa would be great.

**Comment by garnaat** [comment]
I have just merged the python-refactor branch to develop.  This is the main line now and all work will be focused on this going forward.

**Comment by garnaat** [comment]
BTW, the current version in develop does filter out dependencies that are already included in the Lambda container.  So, for example, if your code has a dependency on boto3, it will not be included in the zip file by default because it is already available in the container.

**Comment by josegonzalez** [comment]
Python support is now available in the latest release.
