### ISSUE TITLE
question re log group

### ISSUE THREAD

**Issue by drcabana** [garnaat/kappa#5]
Hi,
On running the step "Run kappa --config <path-to-config> tail to view the functions output in CloudWatch logs", I'm getting an exception:

## console excerpt
stimpy ::‹develop*›  /home/dacaba/repos/kappa/samples/kinesis
» kappa --debug --config config.yml tail                                                                                                                                      1 ↵
2015-01-16 10:14:21,763 - kappa.function - DEBUG - tailing function: KinesisSample
2015-01-16 10:14:21,767 - kappa.log - DEBUG - tailing log group: /aws/lambda/KinesisSample
2015-01-16 10:14:21,767 - kappa.log - DEBUG - getting streams for log group: /aws/lambda/KinesisSample
Traceback (most recent call last):
  File "/usr/local/bin/kappa", line 5, in <module>
    pkg_resources.run_script('kappa==0.1.0', 'kappa')
 ...
 ### stuff elided ###
...
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.
## end console excerpt

For sake of this experiment, I created a kinesis stream, and used its arn to update the config.yml file.  Should I also have created the /aws/lambda/KinesisSample Cloudwatch log group and log stream, or is kappa supposed to be handling that?   

Thank you,
drc

**Comment by garnaat** [comment]
The log group should get created for you by the Lambda service.  Did you do a ``deploy`` prior to the ``tail`` operation?  Did it succeed?

**Comment by drcabana** [comment]
Yes, I ran the deploy step; so far as I can tell it worked. CloudFormation
web gui shows status of CREATE_COMPLETE for the TestKinesis stack, and
TestKinesis Exec and Invoke IAM roles were created.  Also, when I go to the
Lambda web console, I see a function called 'KinesisSample'.   If I click
on the 'logs' link on that page, I am taken to a cloudwatch page, at the
top it says:

Log Groups
<https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logs:>

 Streams for /aws/lambda/KinesisSample
There was an error loading Log Streams. Please try again by refreshing this
page.

No amount of refreshing has any effect.

I found one AWS forum reference to this error message (
https://forums.aws.amazon.com/thread.jspa?messageID=586347 ), but there was
no real resolution.

Misc thoughts:  running in us-east-1,  Python version is 2.7.6, boto
version is 2.34.0.
drc

**Comment by garnaat** [comment]
I haven't seen that behavior before but it certainly sounds as if the creation of the CloudWatch logs for the Kinesis function is either delayed or just isn't going to happen at all.  I'm not sure what I can do about that from the kappa POV although I can certainly handle the error better.

You could try doing a ``kappa delete`` and then another ``kappa deploy`` to see if you get a different result.  The OP in the forum post you link to says that the CloudWatch logs eventually showed up the next day! Kind of gives a new meaning to the term "eventual consistency" 8^)

**Comment by drcabana** [comment]
No worries. I'll keep poking around, will let you know if I learn anything
worth sharing.

**Comment by garnaat** [comment]
I was playing around with this a bit and I noticed that the log group does not get created until the Lambda function actually gets called.  In your situation, had you already tested the function?  Or would this explain why no log group was created for you?

**Comment by chennav** [comment]
I have the same issue, my Lambda was invoked a few hundred times and yet I get the error "There was an error loading Log Streams. Please try again by refreshing this page."
Does this have anything to do with my AWS IAM Role/permissions?

**Comment by LukeSwart** [comment]
This might be a long shot, but I resolved this issue by making sure that the role associated with my Lambda had sufficient permissions to access/write the logs for the lambda function, and after updating the IAM roles, I just deleted and re-created the Lambda function.

You'll want an IAM role for your Lambda role similar to this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "logs:CreateLogGroup",
            "Resource": "arn:aws:logs:us-east-1:123456789101:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": [
                "arn:aws:logs:us-east-1:123456789101:log-group:/aws/lambda/my_lambda_func_1:*",
                "arn:aws:logs:us-east-1:123456789101:log-group:/aws/lambda/my_lambda_func_2:*"
            ]
        }
    ]
```

I don't even use Kappa, but I may try it someday! But I don't think this is a Kappa bug - I think it is an issue with configuring permissions on AWS Lambda, which seems a bit buggy. I just came across this issue on the interwebs. But perhaps this may help someone!

**Comment by josegonzalez** [comment]
Thanks for the bump @LukeSwart :)

**Comment by ishallbethat** [comment]
I don't understand my lambda has full access to cloudwatch and it still has this error
There was an error loading Log Streams. Please try again by refreshing this page.
