### ISSUE TITLE
Use lambda-packages during zip creation

### ISSUE THREAD

**Issue by Miserlou** [garnaat/kappa#55]
Hey garnaat!

It might be cool if Kappa could automatically use the [lambda-packages](https://github.com/Miserlou/lambda-packages) during zip creation, to automatically use lambda-compatible versions of popular dependencies. 

Just a thought,
R

**Comment by josegonzalez** [comment]
That would require rewriting application code to inject them, which I don't think is the right way to go here. It'll almost certainly break user's applications in weird ways, as people often build targeting specific versions of a package.
