### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by wjo1212** [garnaat/kappa#73]
running unit test cases with Py3, failed due to a MD5 compare checking in context.py

**Comment by wjo1212** [comment]
root cause of the issue: 
In Py3, passed in str (unicode format) and returned it in bytes type.
detail: http://pythoncentral.io/encoding-and-decoding-strings-in-python-3-x/

fix:
decode it back to str type in Py3, no impact in Py2

test and passed the unit test cases with both Py2 and Py3.4.1 (the fixing should be compatible with all Py3 versions)

**Comment by josegonzalez** [comment]
I'll have tests run and then merge/release :)
