### ISSUE TITLE
Zip is created uncompressed

### ISSUE THREAD

**Issue by ryansb** [garnaat/kappa#8]
I'm happy to write a fix, but I'm not sure which direction you'd like to go

1. compress the zipfile by default
2. compress the zipfile if a flag is passed (e.g. `--compress`)
3. compress by default, allow a `--no-compress` flag
4. automatically decide based on the size of the zip

Thoughts?

**Comment by garnaat** [comment]
The fact that it was not being compressed was an oversight on my part.  I don't see any reason to perpetuate it.  I would just change it to always do the compress.
