### ISSUE TITLE
Please release Kappa 0.6.1

### ISSUE THREAD

**Issue by Miserlou** [garnaat/kappa#82]
Would be nice if we could get a small version bump after the recent S3-related merge, I'd like to do a new Zappa release today or tomorrow that depends on that commit.

**Comment by Miserlou** [comment]
Bump

**Comment by stonemary** [comment]
+1 also waiting for an important bug fix https://github.com/garnaat/kappa/issues/85
Thank you very much.

**Comment by woqer** [comment]
+1, waiting on #104, #98 and #96

**Comment by josegonzalez** [comment]
I'll get to it when I get to it.

**Comment by josegonzalez** [comment]
Released 0.7.0.

**Comment by Miserlou** [comment]
Would it help if you got new collaborators to maintain this project?

There are many fixes that need to be published - we've been waiting since August. We need a lot of these improvements downstream.

I'd be happy to take over maintaining this project if you don't have the time for it.
