### ISSUE TITLE
Hard-coded excluded_dirs

### ISSUE THREAD

**Issue by scottbouma** [garnaat/kappa#93]
function.py hard-codes 8 directories that will always be excluded.  But this breaks deployment of any projects that happen to use those packages.  I discovered this when the "jmespath" dependency in my project mysteriously refused to be included in the deployed package.  Some code-spelunking revealed the hard-coded list in function.py.

Any chance of just removing that list entirely?  As far as I can tell kappa is not caching any of those dependencies in my src folder anyway, so I don't think it should need to exclude them.

**Comment by kapilt** [comment]
there builtins on the py lambda execution environment which has the boto3 sdk installed.

**Comment by stonemary** [comment]
+1 
Would prefer them to be configurable. We might want to use a specific version of boto or other libraries such that code do not break when AWS change their execution environment.

**Comment by stonemary** [comment]
I will push a PR for them to be configurable.
